[server]
headless = false
runOnSave = false
fileWatcherType = "none"
port = 8501
address = "127.0.0.1"

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"
serverPort = 8501

[theme]
base = "dark"
primaryColor = "#00f0ff"
backgroundColor = "#060913"
secondaryBackgroundColor = "#090e1a"
textColor = "#ffffff"

